on: [pull_request]

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    name: Greeting
    steps:
      - uses: miyajan/javascript-action-pr-comment@releases/v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: Nice PR!ğŸ‘
